/* eslint-disable no-console */
/**
 * Build-time dice-image generator.
 *
 * Reads the 8 hand-authored outline images in assets/dice/{type}.png and burns
 * each die value onto the correct front face, producing one composite PNG per
 * (type, value) in assets/dice/generated/{type}-{value}.png.
 *
 * These composites are used UNCHANGED for both the on-screen preview and the
 * note insertion, so "insert produces the same image as the preview" is true by
 * construction.
 *
 * Also emits src/diceImages.ts: a static require() map RN's bundler can resolve.
 *
 * Run: node scripts/generateDice.js   (or: npm run gen:dice)
 */
const path = require('path');
const fs = require('fs');
const sharp = require('sharp');

const ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'assets', 'dice');
const OUT_DIR = path.join(SRC_DIR, 'generated');
const MAP_FILE = path.join(ROOT, 'src', 'diceImages.ts');

// Output resolution: 2x the 150px insert size, crisp on e-ink, still tiny in b&w.
const OUT = 300;

/**
 * Per-die layout. Each die's number sits centred in its front face, sized to
 * fit the front-face BOX so it never breaks out of the shape.
 *  source     : which outline PNG to draw (d100 reuses the d10 outline).
 *  values     : how many faces (1..N).
 *  cx,cy      : centre of the front face, as a fraction of the canvas.
 *  boxW,boxH  : the front face's usable width/height, as fractions of the
 *               canvas. Font is shrunk to fit BOTH, so 1- and 3-digit values
 *               (e.g. d100's "100") all stay inside the face.
 */
const DICE = {
  d2: { source: 'd2', values: 2, cx: 0.5, cy: 0.5, boxW: 0.5, boxH: 0.4 },
  d4: { source: 'd4', values: 4, cx: 0.43, cy: 0.58, boxW: 0.24, boxH: 0.15 },
  d6: { source: 'd6', values: 6, cx: 0.45, cy: 0.53, boxW: 0.32, boxH: 0.3 },
  d8: { source: 'd8', values: 8, cx: 0.5, cy: 0.44, boxW: 0.26, boxH: 0.15 },
  d10: { source: 'd10', values: 10, cx: 0.5, cy: 0.47, boxW: 0.28, boxH: 0.17 },
  d12: { source: 'd12', values: 12, cx: 0.5, cy: 0.46, boxW: 0.3, boxH: 0.18 },
  d20: { source: 'd20', values: 20, cx: 0.5, cy: 0.49, boxW: 0.22, boxH: 0.14 },
  d100: { source: 'd10', values: 100, cx: 0.5, cy: 0.47, boxW: 0.38, boxH: 0.16 },
};

// Approximate width of one bold-sans glyph relative to font size.
const GLYPH_RATIO = 0.6;

function fontSizeFor(cfg, value) {
  const nchars = String(value).length;
  const byWidth = (cfg.boxW * OUT) / (GLYPH_RATIO * nchars);
  const byHeight = cfg.boxH * OUT; // digit cap-height ≈ 0.7·fontSize, so this fits with margin
  return Math.round(Math.min(byWidth, byHeight));
}

function numberSvg(cfg, value) {
  const fontSize = fontSizeFor(cfg, value);
  const x = Math.round(cfg.cx * OUT);
  const y = Math.round(cfg.cy * OUT);
  return Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${OUT}" height="${OUT}">` +
      `<text x="${x}" y="${y}" font-family="Helvetica, Arial, sans-serif" ` +
      `font-size="${fontSize}" font-weight="bold" text-anchor="middle" ` +
      `dominant-baseline="central" fill="#000">${value}</text>` +
      `</svg>`,
  );
}

async function generate() {
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  // Cache each resized outline so we composite onto it many times.
  const baseCache = {};
  async function base(source) {
    if (!baseCache[source]) {
      const srcPath = path.join(SRC_DIR, `${source}.png`);
      if (!fs.existsSync(srcPath)) {
        throw new Error(`Missing source outline: ${srcPath}`);
      }
      baseCache[source] = await sharp(srcPath)
        .resize(OUT, OUT, { fit: 'contain', background: '#00000000' })
        .png()
        .toBuffer();
    }
    return baseCache[source];
  }

  let count = 0;
  const mapEntries = [];

  for (const [type, cfg] of Object.entries(DICE)) {
    const sides = Number(type.slice(1));
    const baseBuf = await base(cfg.source);
    const valueLines = [];
    for (let value = 1; value <= cfg.values; value++) {
      const outName = `${type}-${value}.png`;
      await sharp(baseBuf)
        .composite([{ input: numberSvg(cfg, value), top: 0, left: 0 }])
        // Pure b&w line art: an 8-colour palette (black + a few anti-alias
        // greys over transparency) keeps every file ~2KB with no visible loss.
        .png({ palette: true, colours: 8, effort: 10, compressionLevel: 9 })
        .toFile(path.join(OUT_DIR, outName));
      valueLines.push(
        `    ${value}: require('../assets/dice/generated/${outName}'),`,
      );
      count++;
    }
    mapEntries.push(`  ${sides}: {\n${valueLines.join('\n')}\n  },`);
  }

  const header =
    '// AUTO-GENERATED by scripts/generateDice.js — do not edit by hand.\n' +
    '// Run `npm run gen:dice` to regenerate after changing source art or layout.\n' +
    "import { ImageSourcePropType } from 'react-native';\n\n" +
    'type DiceImageMap = Record<number, Record<number, ImageSourcePropType>>;\n\n';

  const body =
    'export const DICE_IMAGES: DiceImageMap = {\n' +
    mapEntries.join('\n') +
    '\n};\n\n' +
    '// d100 reuses the d10 outline; every other die maps 1:1 to its own art.\n' +
    'export function diceImage(sides: number, value: number): ImageSourcePropType | undefined {\n' +
    '  const byValue = DICE_IMAGES[sides];\n' +
    '  if (!byValue) return undefined;\n' +
    '  return byValue[value];\n' +
    '}\n';

  fs.writeFileSync(MAP_FILE, header + body);

  console.log(`Generated ${count} dice composites in ${path.relative(ROOT, OUT_DIR)}`);
  console.log(`Wrote require map: ${path.relative(ROOT, MAP_FILE)}`);
}

generate().catch(err => {
  console.error(err);
  process.exit(1);
});
