import React from 'react';
import { View, Text, Image, StyleSheet } from 'react-native';
import { DieType } from './diceUtils';
import { diceImage } from './diceImages';

interface Props {
  sides: DieType;
  value: number;
  size?: number;
}

// Renders a die as the pre-composited outline+number PNG generated by
// scripts/generateDice.js. The same asset is reused for note insertion, so the
// preview and the inserted image are guaranteed identical.
export default function DiceFace({ sides, value, size = 64 }: Props) {
  const source = diceImage(sides, value);

  if (!source) {
    // Fallback for an out-of-range value: show the bare notation.
    return (
      <View style={[styles.wrapper, { width: size, height: size }]}>
        <View style={[styles.fallback, { width: size * 0.85, height: size * 0.85 }]}>
          <Text style={[styles.fallbackText, { fontSize: size * 0.22 }]}>
            d{sides}:{value}
          </Text>
        </View>
      </View>
    );
  }

  return (
    <View style={[styles.wrapper, { width: size, height: size }]}>
      <Image
        source={source}
        style={{ width: size, height: size }}
        resizeMode="contain"
      />
    </View>
  );
}

const styles = StyleSheet.create({
  wrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    margin: 4,
  },
  fallback: {
    borderWidth: 2,
    borderColor: '#000',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fallbackText: {
    color: '#000',
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
