import React from 'react';
import { View, Text, Image, StyleSheet } from 'react-native';
import { DieType } from './diceUtils';
import { diceImage } from './diceImages';

interface Props {
  sides: DieType;
  value: number;
  size?: number;
  // When true, the die is drawn struck through — rolled but not counted
  // (dropped by keep-highest/lowest or advantage/disadvantage).
  struck?: boolean;
}

// A diagonal line across the die, marking it as not counted.
function Strike({ size }: { size: number }) {
  return (
    <View
      pointerEvents="none"
      style={[
        styles.strike,
        {
          width: size * 0.96,
          top: size / 2 - 2,
          left: size * 0.02,
          transform: [{ rotate: '-20deg' }],
        },
      ]}
    />
  );
}

// Renders a die as the pre-composited outline+number PNG generated by
// scripts/generateDice.js. The same asset is reused for note insertion, so the
// preview and the inserted image are guaranteed identical.
export default function DiceFace({ sides, value, size = 64, struck = false }: Props) {
  const source = diceImage(sides, value);

  if (!source) {
    // Fallback for an out-of-range value: show the bare notation.
    return (
      <View style={[styles.wrapper, { width: size, height: size }]}>
        <View style={[styles.fallback, { width: size * 0.85, height: size * 0.85 }]}>
          <Text style={[styles.fallbackText, { fontSize: size * 0.22 }]}>
            d{sides}:{value}
          </Text>
        </View>
        {struck ? <Strike size={size} /> : null}
      </View>
    );
  }

  return (
    <View style={[styles.wrapper, { width: size, height: size }]}>
      <Image
        source={source}
        style={{ width: size, height: size }}
        resizeMode="contain"
      />
      {struck ? <Strike size={size} /> : null}
    </View>
  );
}

const styles = StyleSheet.create({
  wrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    margin: 4,
  },
  fallback: {
    borderWidth: 2,
    borderColor: '#000',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fallbackText: {
    color: '#000',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  strike: {
    position: 'absolute',
    height: 4,
    backgroundColor: '#000',
    borderRadius: 2,
  },
});
